accessControl:
  salt: m0BBXuJ8HZ2N4OFvmZU8yf6yM01mkmoP
api:
  key: 9C6A735189B34BEA9490305BE150F355
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1635237900
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1611568800
      _plugins:
        read_until: 1633410000
      _releases:
        read_until: 1635874200
  bedlevelvisualizer:
    _config_version: 1
    command: 'G80

      @BEDLEVELVISUALIZER

      G81'
    debug_logging: true
    mesh_timestamp: 11/8/2021, 1:16:45 PM
    stored_mesh:
    - - '0.10000'
      - '0.11417'
      - '0.09167'
      - '0.03250'
      - '-0.06333'
      - '-0.19583'
      - '-0.36500'
    - - '0.11444'
      - '0.13330'
      - '0.11488'
      - '0.05917'
      - '-0.03383'
      - '-0.16410'
      - '-0.33167'
    - - '0.12694'
      - '0.14515'
      - '0.12701'
      - '0.07250'
      - '-0.01836'
      - '-0.14559'
      - '-0.30917'
    - - '0.13750'
      - '0.14972'
      - '0.12806'
      - '0.07250'
      - '-0.01694'
      - '-0.14028'
      - '-0.29750'
    - - '0.14611'
      - '0.14701'
      - '0.11802'
      - '0.05917'
      - '-0.02957'
      - '-0.14818'
      - '-0.29667'
    - - '0.15278'
      - '0.13701'
      - '0.09691'
      - '0.03250'
      - '-0.05623'
      - '-0.16929'
      - '-0.30667'
    - - '0.15750'
      - '0.11972'
      - '0.06472'
      - '-0.00750'
      - '-0.09694'
      - '-0.20361'
      - '-0.32750'
    stored_mesh_x:
    - 0
    - 33
    - 67
    - 100
    - 133
    - 167
    - 200
    stored_mesh_y:
    - 0
    - 33
    - 67
    - 100
    - 133
    - 167
    - 200
    stored_mesh_z_height: 200
  discovery:
    upnpUuid: bfc10c0e-960b-448b-ad75-e489cb582aea
  errortracking:
    unique_id: 0a57cfec-a043-44f3-b973-87c41fec6844
  gcodeviewer:
    _config_version: 1
  sensordatavis:
    arduino_baud: '115200'
    arduino_port: /dev/ttyACM1
    lims_endpoint: Facility.PrusaMK3
    lims_port: '8080'
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: d57445c9-3ea0-4149-93fc-9e9e4cd7faf8
  virtual_printer:
    _config_version: 1
    enabled: true
printerProfiles:
  default: _default
serial:
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyACM0
server:
  firstRun: false
  onlineCheck:
    enabled: true
    host: 8.8.8.8
  pluginBlacklist:
    enabled: true
  secretKey: N6EWg4n7RetJoVeSjWOnRl76bKhOTgon
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
