accessControl:
  salt: m0BBXuJ8HZ2N4OFvmZU8yf6yM01mkmoP
api:
  key: 9C6A735189B34BEA9490305BE150F355
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1627392600
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1611568800
      _plugins:
        read_until: 1632718800
      _releases:
        read_until: 1631532900
  discovery:
    upnpUuid: bfc10c0e-960b-448b-ad75-e489cb582aea
  errortracking:
    unique_id: 0a57cfec-a043-44f3-b973-87c41fec6844
  gcodeviewer:
    _config_version: 1
  sensordatavis:
    lims_port: '8080'
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: d57445c9-3ea0-4149-93fc-9e9e4cd7faf8
  virtual_printer:
    _config_version: 1
    enabled: true
printerProfiles:
  default: _default
serial:
  autoconnect: true
  port: VIRTUAL
server:
  firstRun: false
  onlineCheck:
    enabled: true
    host: 8.8.8.8
  pluginBlacklist:
    enabled: true
  secretKey: N6EWg4n7RetJoVeSjWOnRl76bKhOTgon
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
