accessControl:
  salt: m0BBXuJ8HZ2N4OFvmZU8yf6yM01mkmoP
api:
  key: 9C6A735189B34BEA9490305BE150F355
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1635237900
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1611568800
      _plugins:
        read_until: 1633410000
      _releases:
        read_until: 1635874200
  bedlevelvisualizer:
    _config_version: 1
    command: 'G80

      @BEDLEVELVISUALIZER

      G81'
    debug_logging: true
    mesh_timestamp: 11/16/2021, 10:47:44 AM
    stored_mesh:
    - - '-0.11000'
      - '0.04944'
      - '0.16111'
      - '0.22500'
      - '0.24111'
      - '0.20944'
      - '0.13000'
    - - '-0.04194'
      - '0.08269'
      - '0.16583'
      - '0.20750'
      - '0.20769'
      - '0.16639'
      - '0.08361'
    - - '0.01639'
      - '0.10824'
      - '0.16500'
      - '0.18667'
      - '0.17324'
      - '0.12472'
      - '0.04111'
    - - '0.06500'
      - '0.12611'
      - '0.15861'
      - '0.16250'
      - '0.13778'
      - '0.08444'
      - '0.00250'
    - - '0.10389'
      - '0.13630'
      - '0.14667'
      - '0.13500'
      - '0.10130'
      - '0.04556'
      - '-0.03222'
    - - '0.13306'
      - '0.13880'
      - '0.12917'
      - '0.10417'
      - '0.06380'
      - '0.00806'
      - '-0.06306'
    - - '0.15250'
      - '0.13361'
      - '0.10611'
      - '0.07000'
      - '0.02528'
      - '-0.02806'
      - '-0.09000'
    stored_mesh_x:
    - 0
    - 33
    - 67
    - 100
    - 133
    - 167
    - 200
    stored_mesh_y:
    - 0
    - 33
    - 67
    - 100
    - 133
    - 167
    - 200
    stored_mesh_z_height: 200
  discovery:
    upnpUuid: bfc10c0e-960b-448b-ad75-e489cb582aea
  errortracking:
    unique_id: 0a57cfec-a043-44f3-b973-87c41fec6844
  gcodeviewer:
    _config_version: 1
  sensordatavis:
    arduino_baud: '115200'
    lims_endpoint: Facility.PrusaMK3
    lims_port: '8080'
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: d57445c9-3ea0-4149-93fc-9e9e4cd7faf8
  virtual_printer:
    _config_version: 1
    enabled: true
printerProfiles:
  default: _default
serial:
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyACM1
server:
  firstRun: false
  onlineCheck:
    enabled: true
    host: 8.8.8.8
  pluginBlacklist:
    enabled: true
  secretKey: N6EWg4n7RetJoVeSjWOnRl76bKhOTgon
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
