accessControl:
  salt: m0BBXuJ8HZ2N4OFvmZU8yf6yM01mkmoP
api:
  key: 9C6A735189B34BEA9490305BE150F355
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1635237900
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1611568800
      _plugins:
        read_until: 1633410000
      _releases:
        read_until: 1635874200
  bedlevelvisualizer:
    _config_version: 1
    command: 'G80

      @BEDLEVELVISUALIZER

      G81'
    debug_logging: true
    mesh_timestamp: 11/15/2021, 11:05:39 AM
    stored_mesh:
    - - '-0.05500'
      - '0.09139'
      - '0.19472'
      - '0.25500'
      - '0.27222'
      - '0.24639'
      - '0.17750'
    - - '-0.00389'
      - '0.12247'
      - '0.20904'
      - '0.25583'
      - '0.26284'
      - '0.23006'
      - '0.15750'
    - - '0.03944'
      - '0.14506'
      - '0.21469'
      - '0.24833'
      - '0.24599'
      - '0.20765'
      - '0.13333'
    - - '0.07500'
      - '0.15917'
      - '0.21167'
      - '0.23250'
      - '0.22167'
      - '0.17917'
      - '0.10500'
    - - '0.10278'
      - '0.16478'
      - '0.19997'
      - '0.20833'
      - '0.18988'
      - '0.14460'
      - '0.07250'
    - - '0.12278'
      - '0.16191'
      - '0.17960'
      - '0.17583'
      - '0.15062'
      - '0.10395'
      - '0.03583'
    - - '0.13500'
      - '0.15056'
      - '0.15056'
      - '0.13500'
      - '0.10389'
      - '0.05722'
      - '-0.00500'
    stored_mesh_x:
    - 0
    - 33
    - 67
    - 100
    - 133
    - 167
    - 200
    stored_mesh_y:
    - 0
    - 33
    - 67
    - 100
    - 133
    - 167
    - 200
    stored_mesh_z_height: 200
  discovery:
    upnpUuid: bfc10c0e-960b-448b-ad75-e489cb582aea
  errortracking:
    unique_id: 0a57cfec-a043-44f3-b973-87c41fec6844
  gcodeviewer:
    _config_version: 1
  sensordatavis:
    arduino_baud: '115200'
    lims_endpoint: Facility.PrusaMK3
    lims_port: '8080'
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: d57445c9-3ea0-4149-93fc-9e9e4cd7faf8
  virtual_printer:
    _config_version: 1
    enabled: true
printerProfiles:
  default: _default
serial:
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyACM1
server:
  firstRun: false
  onlineCheck:
    enabled: true
    host: 8.8.8.8
  pluginBlacklist:
    enabled: true
  secretKey: N6EWg4n7RetJoVeSjWOnRl76bKhOTgon
  seenWizards:
    backup: null
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
